services:
  - type: web
    name: bookstoreapp
    runtime: docker
    repo: https://github.com/yogesh-hack/techbooklibrary
    branch: main
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: connectoinstring..

